### ISSUE TITLE
[Refactor] 라우팅 수정 - TODO: API 연결 시작할 때 작업

### ISSUE THREAD

**Issue by youjin-hong** [prgrms-web-devcourse-final-project/WEB1_1_Bongdari_FE#83]
## 어떤 기능인가요?

멘토링 피드백 반영해 라우팅 이름을 수정하려 합니다.

## 작업 상세 내용

- [ ] 메인 페이지 -> "/"

**백엔드에서 보내주는 volunteer, center 타입에 따라 다른 페이지 컴포넌트 부여**
- [ ] 로그인 -> 기관/봉사자 "/login"
- [ ] 마이페이지 -> 기관/봉사자 "/myPage"
- [ ] 프로필 -> 기관/봉사자 "/profile"
